import type { NextPage } from "next";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect } from "react";

const Home: NextPage = () => {
  //const m = trpc.useMutation("recipe.insertTests");
  const router = useRouter();
  useEffect(() => {
    // m.mutate();
    router.push("/recipes");
  }, []);

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container flex flex-col h-screen p-4 mx-auto"></main>
    </>
  );
};

export default Home;
